### PR TITLE
Fix GitHub actions failing

### PR DESCRIPTION
**Pull request by robertjcolley**

### CODE REVIEW

**Comment by hannesa2** [comment]
I observed this: there is no longer an active maintainer to merge stuff

**Comment by mariansam** [comment]
@hannesa2 that's starting to change

**Comment by hannesa2** [comment]
> @hannesa2 that's starting to change

Maybe. I wrote/offered @doranteseduardo via email and Discord about maintenance. But I got no response at all

**Comment by robertjcolley** [comment]
> > @hannesa2 that's starting to change
> 
> Maybe. I wrote/offered @doranteseduardo via email and Discord about maintenance. But I got no response at all

Hi @hannesa2, I'm working with @cjmcassar to create a roadmap and start fixing issues and creating a new vision for the project. I'd love to meet with you and talk about maintenance! Shoot me a message on discord at .bcolley or email me at robertcolley04@gmail.com!

**Comment by robertjcolley** [comment]
There's a bigger issue here, which is that we depend on GVRAudioSdk which has been deprecated. I checked following [these instructions](https://stackoverflow.com/a/43778639) and it turns out that GVRAudioSDK includes bitcode, which is not allowed on xCode 14. I'm pretty sure this is why the linking is failing on xCode 14 and not the xCode 13 GitHub action.

image

I would push for GVRAudioSDK being replaced with a different library. I looked at the Google Cardboard SDK, but I couldn't find any reference to spacial audio. We only used GVRAudioSDK for spacial audio in a handful of files.

I also get the sense that GVR should be deprecated and removed from Viro and we should look for alternatives like [Cardboard](https://github.com/googlevr/cardboard) or something else. Both [iOS](https://developer.apple.com/news/?id=fakg1z5b) and [Android](https://developer.android.com/media/grow/spatial-audio) have spatial audio SDKs that can be a replacement for GVRAudioSDK.

**Pull request closed without merging**
